version: '3.8'

services:
  microhap-fastapi:
    build:
      context: ./microhapDB-backend/
      dockerfile: Dockerfile
    volumes:
      - ./microhapDB-backend/src:/code/src
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:bipostgres@database-1.czwgjenckjul.us-east-2.rds.amazonaws.com:5432/haplosearch
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge