apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-processing-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
