version: '3.8'

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=microhaplotype
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=bipostgres
    networks:
      - app-network

  microhap-fastapi:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/code/src
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres_user:bipostgres@postgres/microhaplotype
    depends_on:
      - postgres
    networks:
      - app-network

  microhap-frontend:
    image: microhapdb-frontend
    ports:
      - "8080:80"
    depends_on:
      - microhap-fastapi
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
